version: "3.4"

services:
  solaiman.me:
    image: npx:latest
    volumes:
      - ${PWD}:/usr/src/app
    container_name: solaiman.me
    ports:
      - "4000:4000"
    command: hexo server
  
  generate:
    image: npx:latest
    volumes:
      - ${PWD}:/usr/src/app
    command: hexo generate
  
  deploy:
    image: npx:latest
    volumes:
      - ${PWD}:/usr/src/app
    command: hexo deploy
