version: '2'
services:
  solaiman.me:
    container_name: solaiman.me
    image: alxshelepenok/gatsby-starter-lumen:development
    build:
      context: ./
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    command: |
      gatsby develop -H 0.0.0.0
